import React, { useState } from 'react';
import { Gavel, Plus, Edit, Trash2 } from 'lucide-react';

export default function RulesView({ rules, onSaveRule, onDeleteRule, isReadOnly }) {
  const [isEditing, setIsEditing] = useState(false);
  const [editRule, setEditRule] = useState({ topic: "", score: 0, type: "deduct", detail: "" });
  const handleEditClick = (rule) => { setEditRule(rule); setIsEditing(true); };
  const handleAddClick = () => { setEditRule({ topic: "", score: 0, type: "deduct", detail: "" }); setIsEditing(true); };
  const handleSubmit = (e) => { e.preventDefault(); onSaveRule({ ...editRule, id: editRule.id || Date.now().toString() }); setIsEditing(false); setEditRule({ topic: "", score: 0, type: "deduct", detail: "" }); };

  return (
    <div className="space-y-6 animate-fade-in">
      <div className="flex justify-between items-center">
        <h2 className="text-2xl font-bold text-gray-800 flex items-center gap-2"><Gavel className="text-blue-600" /> ระเบียบการหัก/เพิ่ม คะแนน</h2>
        {!isReadOnly && <button onClick={handleAddClick} className="flex items-center gap-2 bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition"><Plus size={18} /> เพิ่มกฎใหม่</button>}
      </div>
      {isEditing && !isReadOnly && (
        <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100 mb-6"><h3 className="font-bold mb-4">{editRule.id ? 'แก้ไขกฎระเบียบ' : 'เพิ่มกฎระเบียบใหม่'}</h3><form onSubmit={handleSubmit} className="grid grid-cols-1 md:grid-cols-2 gap-4"><div className="md:col-span-2"><label className="block text-xs font-semibold text-gray-500 mb-1">หัวข้อ</label><input required className="w-full border rounded px-3 py-2" value={editRule.topic || ""} onChange={e => setEditRule({...editRule, topic: e.target.value})} /></div><div><label className="block text-xs font-semibold text-gray-500 mb-1">ประเภท</label><select className="w-full border rounded px-3 py-2" value={editRule.type} onChange={e => setEditRule({...editRule, type: e.target.value})}><option value="deduct">หักคะแนน (-)</option><option value="add">เพิ่มคะแนน (+)</option></select></div><div><label className="block text-xs font-semibold text-gray-500 mb-1">คะแนน</label><input type="number" required className="w-full border rounded px-3 py-2" value={Math.abs(editRule.score) || 0} onChange={e => setEditRule({...editRule, score: editRule.type === 'deduct' ? -Math.abs(e.target.value) : Math.abs(e.target.value)})} /></div><div className="md:col-span-2"><label className="block text-xs font-semibold text-gray-500 mb-1">รายละเอียด</label><input className="w-full border rounded px-3 py-2" value={editRule.detail || ""} onChange={e => setEditRule({...editRule, detail: e.target.value})} /></div><div className="md:col-span-2 flex justify-end gap-2"><button type="button" onClick={() => setIsEditing(false)} className="px-4 py-2 text-gray-600 hover:bg-gray-100 rounded">ยกเลิก</button><button type="submit" className="px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700">บันทึก</button></div></form></div>
      )}
      <div className="bg-white rounded-xl shadow-sm overflow-hidden"><table className="min-w-full divide-y divide-gray-200"><thead className="bg-gray-50"><tr><th className="px-6 py-3 text-left text-xs font-bold text-gray-500 uppercase">หัวข้อ</th><th className="px-6 py-3 text-left text-xs font-bold text-gray-500 uppercase">รายละเอียด</th><th className="px-6 py-3 text-center text-xs font-bold text-gray-500 uppercase">คะแนน</th>{!isReadOnly && <th className="px-6 py-3 text-right text-xs font-bold text-gray-500 uppercase">จัดการ</th>}</tr></thead><tbody className="bg-white divide-y divide-gray-200">{rules.map(rule => (<tr key={rule.docId || rule.id} className="hover:bg-gray-50"><td className="px-6 py-4 font-medium text-gray-800">{rule.topic}</td><td className="px-6 py-4 text-sm text-gray-500">{rule.detail}</td><td className="px-6 py-4 text-center"><span className={`px-2 py-1 rounded text-xs font-bold ${rule.score > 0 ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700'}`}>{rule.score > 0 ? '+' : ''}{rule.score}</span></td>{!isReadOnly && <td className="px-6 py-4 text-right flex justify-end gap-2"><button onClick={() => handleEditClick(rule)} className="text-blue-500 hover:bg-blue-50 p-1 rounded"><Edit size={16} /></button><button onClick={() => onDeleteRule(rule.id)} className="text-red-500 hover:bg-red-50 p-1 rounded"><Trash2 size={16} /></button></td>}</tr>))}</tbody></table></div>
    </div>
  );
}